### ISSUE TITLE
Help me open and edit this .JDM file [$100]

### ISSUE THREAD

**Issue by TGDTom** [TGDTom/automotive_jdm_file#1]
Check the README in main for more information about the file and the reward.

**Comment by modrobert** [comment]
By the looks of it, the file 'bmw_010206c.jdm.jdm' includes CAN bus (UDS) messages for a specific controller, the information sent to the controller is either encrypted or compressed. The file is in 16 byte blocks with 0xFF separator between each block.

https://en.wikipedia.org/wiki/CAN_bus

**Comment by TGDTom** [comment]
Hi there Robert,

Do you see any opportunity to decrypt this? There's a $100 reward on bountysource if you're interested!

Kind regards.

________________________________
Van: modrobert <notifications@github.com>
Verzonden: woensdag 27 januari 2021 05:09
Aan: TGDTom/automotive_jdm_file <automotive_jdm_file@noreply.github.com>
CC: TGDTom <tom.rassaerts@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [TGDTom/automotive_jdm_file] Help me open and edit this .JDM file [$100] (#1)


By the looks of it, the file 'bmw_010206c.jdm.jdm' includes CAN bus (UDS) messages for a specific controller, the information sent to the controller is either encrypted or compressed. The file is in 16 byte blocks with 0xFF separator between each block.

https://en.wikipedia.org/wiki/CAN_bus
